#!/usr/bin/env php
<?php
if($argc < 3) {
    echo "Usage: gitmirror <source git path> <target git path>\r\n";
    exit;
}

$source = $argv[1];
$target = $argv[2];
$tempFolder = "t" . md5(mt_rand(1,100) . time());
shell_exec("git clone --mirror " . $source . " " . $tempFolder);
shell_exec("cd " . $tempFolder . " && git push --mirror " . $target);
shell_exec("rm -rf " . $tempFolder);
echo "\r\n\r\nDone!\r\n";
?>
